### ISSUE TITLE
Unexpected .DS_Store

### ISSUE THREAD

**Issue by Lodour** [CrispMoon/CrispMoon.github.io#2]
Please remove your `.DS_Store` files.

**Comment by Lodour** [comment]
Why don't you make a reply?

**Comment by CrispMoon** [comment]
.....because i m cool

**Comment by Lodour** [comment]
@CrispMoon COME ON!

**Comment by Lodour** [comment]
Issue #4 may be closed automatically if you just mention it in this merge action's description.
